### ISSUE TITLE
Problems on macOS

### ISSUE THREAD

**Issue by paulocoutinhox** [houmain/spright-vscode#2]
Hi,

Im getting this error:
Downloading spright 3.3.0 for darwin/arm64 failed.

Can you help me?

Last version was in 2023.

**Comment by houmain** [comment]
Hi, thanks for reporting. 
There is now a [spright-3.4.0-Darwin-arm64](https://github.com/houmain/spright/releases) build, which should work on MacOS/arm64. The new version 1.2.1 of the extension should automatically use it.

**Comment by houmain** [comment]
Hi, can you confirm that it works for you now?

**Comment by paulocoutinhox** [comment]
Hi, it is working now.
